version: "1"
rules:
  - base: master
    upstream: TrustyJAID:master    # change `wei` to the owner of upstream repo
    mergeMethod: hardreset
    mergeUnstable: true
  - base: lucifer-bot
    upstream: TrustyJAID:master
    mergeMethod: merge
    mergeUnstable: true
    conflictReviewers:
      - jack1142
label: ":arrow_heading_down: update fork from upstream"
